databases:
  - name: antrodia-db
    databaseName: antrodia
    user: antrodia
    plan: free # Note: Render Free Tier PostgreSQL expires after 90 days
    region: singapore

services:
  - type: web
    name: antrodia-biotech
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn antrodia_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: antrodia-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
